### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by RyanRHall** [KCostanzo/CloudSound#4]
-- Give yourself  more time for frontend auth -- 1 full day.
-- You have create song model in both phase 2 & 3
-- CSS styling should not be a phase. You should style all components to completion as you go.
   -- Instead, maybe you could devote 1/2 a day to layout and redistribute the other half-day to other phases.
-- Seeding should happen EARLY so you can test your components and api and pretty much everything..
    -- Save just 1 day for cleanup and UI feedback

**Comment by KCostanzo** [comment]
cool thanks Ryan,

I'll adjust my proposal shortly
